### ISSUE TITLE
Trouble with skip-links and favicon

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/web-design-2-independent-project#6]
I deleted the skip-links I added because they were changing the whole layout of my design. I also didn't realize about the favicon, how would I go about that? @thatkidmadrid

**Comment by thatkidmadrid** [comment]
## Skip-links
Here is the resource with some handy styling already that will help you set up your skip links in a way that doesn't break your layout and appears when it has keybaord focus

https://learn-the-web.algonquindesign.ca/topics/accessibility-cheat-sheet/#html-semantics

## Favicon
Here is the resource that will show you how to set up the favicons, where to put them, and how to include them in your html. I think the week 12 or 13 class recording has a walkthrough of how I set my favicon up. Ignore the tools listed to generate the ico files. Use https://favicon.io/favicon-converter/ instead

https://learn-the-web.algonquindesign.ca/topics/image-formats/#favicons

**Comment by adrianna16** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
