### ISSUE TITLE
Skip Links

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/web-design-2-independent-project#7]
I followed the cheat sheet link that you sent me and I still cannot get it to do what I want. I also figured out the favicon thing but when I try to link the favicon-196.png to the top of my pages it keeps telling me I am wrong. I don't know what to do and I am starting to get discouraged. @thatkidmadrid

**Comment by thatkidmadrid** [comment]
Can you please include more details? a screenshot of markbot would help clarify too

**Comment by thatkidmadrid** [comment]
- the type for the png favicon is `type="image/png"` not `type="images/png"`
- I don't see the skip-links in your html or css

**Comment by thatkidmadrid** [comment]
I cloned your repo and tried the skip link stuff and it's working fine, you're just missing some ids

I've gone through and fixed things on my end to see what else is needed to be able to submit and it's not much more. my advice is to read what markbot is telling you.

Here are some tips that will also help:

- you will want to move all content that isn't inside a wrapper with a role to one that does have a role. For instance, your article with just an image shouild probably either go in the header or main.
- you're missing some alt attributes
- markbot is looking for links inside your main. an easy win is to make your drink images into links.
